---
title: "P8105_hw6_zf2211"
author: "Francis"
date: "11/25/2018"
output: github_document
---



```{r}
# Load packages
library(tidyverse)
library(rvest)
library(modelr)
library(mgcv)
```

# Problem 1



```{r}
# read data
homicide <- read.csv("./data/homicide-data.csv")
```

```{r}
#Create a city_state variable
homicide <- 
  homicide %>% 
  mutate(city_state = str_c(city, ",", state)) %>% 
  select(-city, -state)

# remove city_state, solved is num. 
homicide <- 
  homicide %>% 
  filter(!city_state %in% c("Dallas,TX", "Phoenix,AZ", "Kansas City,MO", "Tulsa,AL")) %>% 
  mutate(solved = as.numeric(disposition == "Closed by arrest"))
```


```{r}
# modifiy victim_race
homicide  <-  
  homicide %>% 
  mutate(victim_race = as_factor(ifelse(victim_race == "White", "white","non-white"))) %>% 
  mutate(victim_race = fct_relevel(victim_race, "white")) %>% 
  mutate(victim_age = as.numeric(victim_age)) 
```


```{r}
### logistic regression
# fit and save
fit_logis <-  
  homicide %>% 
  filter(city_state == "Baltimore,MD") %>% 
  glm(solved ~ victim_age + victim_sex + victim_race, data = ., family = binomial()) 

# obtain the estimate and confidence interval of the adjusted odds ratio for Baltimore,MD
tibble_left <-  
  fit_logis %>% 
  broom::tidy() %>% 
  mutate(OR_estimate = exp(estimate)) %>% 
  select(term, OR_estimate, p.value)
tibble_right = as_tibble(exp(confint.default(fit_logis)))
cbind(tibble_left, tibble_right) %>% 
  knitr::kable(digits = 3)
```



```{r}
# run glm for every city

glm_every <-  
  homicide %>% 
  group_by(city_state) %>% 
  nest() %>% 
  mutate(models = map(data, ~glm(solved ~ victim_age + victim_sex + victim_race, data = ., family = binomial())), 
         results = map(.x = models, ~ broom::tidy(.x, exponentiate = TRUE, conf.int = TRUE))) %>% 
  select(-data, -models) %>% 
  unnest() %>% 
  filter(term == "victim_racenon-white") %>% 
  select(city_state, OR = estimate, conf.low, conf.high)
  
glm_every %>% 
  head() %>% 
  knitr::kable(digits = 3)
```





```{r}
# plot estimated ORs and CIs
glm_every %>% 
  mutate(city_state = as.factor(city_state), 
         city_state = fct_reorder(city_state, desc(OR))) %>% 
  ggplot(aes(x = city_state, y = OR)) +
  geom_point() + 
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
  theme(axis.text.x = element_text(angle = 90, size = rel(0.8), hjust = 1)) +
  labs(
    title = "Variation of OR with cities",
    x = "City/State",
    y = "OR"
  )
```


For most of the cities, the estimates for odds ratio(OR) are below 1.0(1.0 are not included in their 95% CI). So, comparing to white victims for those cities, there is significantly lower estimated odds of solving homicides among non-white victims. The CI for some cities (such as Boston,MA) are narrow, so be can be more confident in future predictions to these cities.





# Problem 2



```{r}
# read data
bwt <- read_csv("./data/birthweight.csv")
```




```{r}
#tidy data
bwt <-  
  bwt %>% 
  mutate(babysex = babysex -1, # male = 0, female = 1
         babysex = as.factor(babysex),
         frace = as.factor(frace),
         malform = as.factor(malform),
         mrace = as.factor(mrace))
# missing values
bwt[which(!complete.cases(bwt)),]           
```

```{r}
# correlation matrix
bwt %>% 
  select(-babysex, -frace, -mrace, -malform) %>% 
  cor()
```
